[base]
env_name = rcssfull
checkpoint_interval=200

[selfplay]
enabled = 0

[vec]
total_agents = 3078
num_buffers = 2
num_threads = 18

[policy]
hidden_size = 128
num_layers = 4

[env]
side = 0
synch_mode = 1
use_monitor = 0
starting_horizon_ticks = 150
step_reward = -0.002
goal_reward = 3
fault_reward = -2
no_goal_timeout = 250
no_goal_reward = -2

[train]
; Longer rollouts + larger minibatches cut train overhead per step.
; Constraints: minibatch_size % horizon == 0, minibatch_size <= horizon * total_agents
horizon = 256
total_timesteps = 7_000_000_000
learning_rate = 0.01
min_lr_ratio = 0.1
ent_coef = 0.005
gamma = 0.995
minibatch_size = 32768

[sweep]
downsample = 2000
; gpus = 1
; max_runs = 80
; max_suggestion_cost = 300
; sweep_only = total_timesteps,learning_rate,ent_coef,gamma,gae_lambda,horizon,replay_ratio,hidden_size

; [sweep.train.total_timesteps]
; distribution = log_normal
; min = 3e7
; max = 1e8
; scale = time

; [sweep.train.learning_rate]
; distribution = log_normal
; min = 0.0003
; max = 0.03
; scale = 0.5

; [sweep.train.ent_coef]
; distribution = log_normal
; min = 0.00001
; max = 0.05
; scale = auto

; [sweep.train.gamma]
; distribution = logit_normal
; min = 0.95
; max = 0.999
; scale = auto

; [sweep.train.gae_lambda]
; distribution = logit_normal
; min = 0.8
; max = 0.99
; scale = auto

; [sweep.train.horizon]
; distribution = uniform_pow2
; min = 64
; max = 512
; scale = auto

; [sweep.train.replay_ratio]
; distribution = uniform
; min = 0.5
; max = 3.0
; scale = auto

; [sweep.policy.hidden_size]
; distribution = uniform_pow2
; min = 64
; max = 256
; scale = auto
